# Generated by Django 3.0.5 on 2022-06-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Searches',
            new_name='Search',
        ),
    ]
